name: Subhendu Khatuya's blog
title: Subhendu Khatuya
url: https://subhendukhatuya.github.io/
baseurl: ""
twitter_username:
github_username:  subhendukhatuya
linkedin_username: subhendu-khatuya-543140a8
description: Machine learning, Deep learning, NLP, Computer Vision and other areas of data science.
# email: sanakarshan7@gmail.com
permalink: /blog/:year/:month/:day/:title
theme: minima

# Conversion
markdown: kramdown

plugins:
  - "disqus-for-jekyll"
  - jekyll-feed
  - jemoji

header_pages:
  #- resume.md
  - publications.md
  - blog/index.html
  - index.md
  - projects.md
